CREATE TABLE AGENT_INFO (
	AGENT_ID INT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR(64),
    OFFICE_ID INT,
    UPLOADED_DATE DATE DEFAULT (CURRENT_DATE),
    PHONE VARCHAR(10),
    EMAIL VARCHAR(23),
    INDEX (AGENT_ID)
    FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE_INFO(OFFICE_ID)
);