/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package company.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;Company_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>company.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>company.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author sam
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee.
	 *
	 * @return the uuid of this employee
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this employee.
	 *
	 * @param uuid the uuid of this employee
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the employees ID of this employee.
	 *
	 * @return the employees ID of this employee
	 */
	public long getEmployeesId();

	/**
	 * Sets the employees ID of this employee.
	 *
	 * @param employeesId the employees ID of this employee
	 */
	public void setEmployeesId(long employeesId);

	/**
	 * Returns the surname of this employee.
	 *
	 * @return the surname of this employee
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this employee.
	 *
	 * @param surname the surname of this employee
	 */
	public void setSurname(String surname);

	/**
	 * Returns the name of this employee.
	 *
	 * @return the name of this employee
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this employee.
	 *
	 * @param name the name of this employee
	 */
	public void setName(String name);

	/**
	 * Returns the patronymic of this employee.
	 *
	 * @return the patronymic of this employee
	 */
	@AutoEscape
	public String getPatronymic();

	/**
	 * Sets the patronymic of this employee.
	 *
	 * @param patronymic the patronymic of this employee
	 */
	public void setPatronymic(String patronymic);

	/**
	 * Returns the sex of this employee.
	 *
	 * @return the sex of this employee
	 */
	@AutoEscape
	public String getSex();

	/**
	 * Sets the sex of this employee.
	 *
	 * @param sex the sex of this employee
	 */
	public void setSex(String sex);

	/**
	 * Returns the birth day of this employee.
	 *
	 * @return the birth day of this employee
	 */
	public Date getBirthDay();

	/**
	 * Sets the birth day of this employee.
	 *
	 * @param birthDay the birth day of this employee
	 */
	public void setBirthDay(Date birthDay);

	/**
	 * Returns the position of this employee.
	 *
	 * @return the position of this employee
	 */
	public int getPosition();

	/**
	 * Sets the position of this employee.
	 *
	 * @param position the position of this employee
	 */
	public void setPosition(int position);

	/**
	 * Returns the date of employment of this employee.
	 *
	 * @return the date of employment of this employee
	 */
	public Date getDateOfEmployment();

	/**
	 * Sets the date of employment of this employee.
	 *
	 * @param dateOfEmployment the date of employment of this employee
	 */
	public void setDateOfEmployment(Date dateOfEmployment);

	/**
	 * Returns the salary of this employee.
	 *
	 * @return the salary of this employee
	 */
	public int getSalary();

	/**
	 * Sets the salary of this employee.
	 *
	 * @param salary the salary of this employee
	 */
	public void setSalary(int salary);

	/**
	 * Returns the mobile phone of this employee.
	 *
	 * @return the mobile phone of this employee
	 */
	public int getMobilePhone();

	/**
	 * Sets the mobile phone of this employee.
	 *
	 * @param mobilePhone the mobile phone of this employee
	 */
	public void setMobilePhone(int mobilePhone);

	/**
	 * Returns the job phone of this employee.
	 *
	 * @return the job phone of this employee
	 */
	public int getJobPhone();

	/**
	 * Sets the job phone of this employee.
	 *
	 * @param jobPhone the job phone of this employee
	 */
	public void setJobPhone(int jobPhone);

	/**
	 * Returns the bank of this employee.
	 *
	 * @return the bank of this employee
	 */
	public int getBank();

	/**
	 * Sets the bank of this employee.
	 *
	 * @param bank the bank of this employee
	 */
	public void setBank(int bank);

	/**
	 * Returns the archive of this employee.
	 *
	 * @return the archive of this employee
	 */
	public boolean getArchive();

	/**
	 * Returns <code>true</code> if this employee is archive.
	 *
	 * @return <code>true</code> if this employee is archive; <code>false</code> otherwise
	 */
	public boolean isArchive();

	/**
	 * Sets whether this employee is archive.
	 *
	 * @param archive the archive of this employee
	 */
	public void setArchive(boolean archive);

}